### ISSUE TITLE
Hide video

### ISSUE THREAD

**Issue by Harxy** [Harxy/Jschat#100]
for music rooms/ swf rooms

**Comment by meadsteve** [comment]
it says music/sfw rooms but maybe we should just have a button like the mute button?

**Comment by johndarv** [comment]
I think a "Hide" button would be good. Maybe persist hide true/false in the cookie as well? So videos don't automatically play every time you log in or refresh.

**Comment by Harxy** [comment]
Oh yeah I didn't mean specifically for those room types. Just so that you can control it, like John says. Cookies is a good idea

**Comment by faroligo** [comment]
@meadsteve @harxy Thoughts on storing mute and hide video preferences in a cookie... do it or reset every time?

**Comment by Harxy** [comment]
hide - save, mute - reset? just my first impulse :)

**Comment by meadsteve** [comment]
I'm leaning towards the same as @Harxy . In any case we have clear icons so it wouldn't take too long to figure out.

**Comment by meadsteve** [comment]
in fact actually ignore that. I think store both. if I close the browser and re-open I don't want it suddenly blaring out music.
