### ISSUE TITLE
Persist play queue contents

### ISSUE THREAD

**Issue by meadsteve** [Harxy/Jschat#101]
Questions:
1. Redis again?
2. Should we persist the current song and position? Or just the upcoming songs.

**Comment by faroligo** [comment]
1. Yes, I reckon
2. I feel like ideally the song and position as well so that we can release as often as we want seamlessly, but I don't know how practical that would be

**Comment by meadsteve** [comment]
1. Shouldn't actually be too hard now that I think about it. Though I'd continue to store the start time rather than the position. Otherwise songs will jump backwards on a reload.
