### ISSUE TITLE
Ability to see who is currently active/logged in

### ISSUE THREAD

**Issue by johndarv** [Harxy/Jschat#11]

**Comment by faroligo** [comment]
I know this will be really useful but there is something quite fun about not knowing who is out there!

**Comment by meadsteve** [comment]
maybe we could implement it as "ping me oli" and if someone called oli is connected you get a pong back?

**Comment by Harxy** [comment]
Nica idea!

**Comment by faroligo** [comment]
In progress ... need to make a PR from the code we wrote at the pub.  Its workingish in its most basic form.  Needs some refactoring
