### ISSUE TITLE
Messages lost when Heroku deploys

### ISSUE THREAD

**Issue by faroligo** [Harxy/Jschat#37]
Due to the local JSON file being removed on deployment.  This also seems to happen when the site isnt used for a while.

We will need to look at a DB instead.

**Comment by meadsteve** [comment]
It's quite easy to add redis to a heroku instance: https://elements.heroku.com/addons/heroku-redis. The free instance should be more than enough for the 30 messages we'll be storing.

**Comment by Harxy** [comment]
I might have a look at that today as it is way out of my comfort zone :)

**Comment by meadsteve** [comment]
So after talking with @Harxy if no-one needs this in the next few days I'll be doing this on wednesday night and screenheroing (https://screenhero.com/) as I do it. Disclaimer: I've never used screen hero before or done anything like this.

But if you want to see how I git and javascript the things. Come on down.

**Comment by Harxy** [comment]
@meadsteve I believe that screenhero is one on one only so you may have to google hangout it, but other than that, keen!

**Comment by meadsteve** [comment]
awww that's a shame. Well in that case, as you've suggested, it may be a google hangout instead.

**Comment by meadsteve** [comment]
@Harxy hooray!: http://blog.screenhero.com/post/110558292401/group-screen-sharing

**Comment by Harxy** [comment]
neato!

**Comment by faroligo** [comment]
@meadsteve yeah, great idea.  Was looking at redis as an option.  Wont be able to join, but good approach.

**Comment by meadsteve** [comment]
Fixed by #55
