### ISSUE TITLE
Project is missing tests

### ISSUE THREAD

**Issue by meadsteve** [Harxy/Jschat#49]
I like tests.

**Comment by meadsteve** [comment]
My vote would be for http://blog.codeship.com/jasmine-node-js-application-testing-tutorial/

**Comment by Harxy** [comment]
Sounds good. Depending how much I do today I may pick this up. Always good to practice your tests!

**Comment by meadsteve** [comment]
Since we'll be building on this project a bit more I'm gonna take a quick look today and see if I can get this in place.
