### ISSUE TITLE
Connection to jschat sometimes get dropped.

### ISSUE THREAD

**Issue by meadsteve** [Harxy/Jschat#54]
Not sure if this is a problem or not. I noticed the following in my chrome console:

```
WebSocket is already in CLOSING or CLOSED state.Faye.Transport.WebSocket.Faye.extend.Faye.Class._ping @ faye.js:2
12faye.js:2 WebSocket connection to 'wss://murmuring-headland-2196.herokuapp.com/faye' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
faye.js:2 WebSocket connection to 'wss://murmuring-headland-2196.herokuapp.com/faye' failed: Error in connection establishment: net::ERR_NETWORK_CHANGED
```

we might need to do something that tries reconnecting after X if the connection is dropped.

**Comment by faroligo** [comment]
This is getting really annoying now.  One of us is going to have to tackle this!!

**Comment by meadsteve** [comment]
at the risk of causing myself some headaches: I can look in to this next week.

**Comment by faroligo** [comment]
Good man!! We can arrange screen hero for some collaborative brainstorming if it proves troublesome.

**Comment by Harxy** [comment]
Oooh I'd like to be in on that!

**Comment by meadsteve** [comment]
@Harxy if #91 works then we won't be having this screen hero.

#84 might be good for some screen hero pairing.
