### ISSUE TITLE
feature: roomcursion me #room

### ISSUE THREAD

**Issue by meadsteve** [Harxy/Jschat#59]
typing `roomcursion me #room` should insert and iframe pointing to that room into the room.

Thoughts?

**Comment by meadsteve** [comment]
alternative name: `roomception me`?

**Comment by Harxy** [comment]
I guess I only have one question.... Why?!?!?

**Comment by meadsteve** [comment]
@Harxy I don't understand your question

**Comment by Harxy** [comment]
Oooooh you can do a different room! I thought you meant the same room. In which case, awesome, go for it. Best feature ever.
