### ISSUE TITLE
Show upcoming video(s) in some way

### ISSUE THREAD

**Issue by meadsteve** [Harxy/Jschat#92]
Suggestions: 
1. Just the next video and who queued it.
2. List of who queued the next X videos.
3. Just a count of the number of videos in the queue.

Thoughts?

**Comment by faroligo** [comment]
I like 2 and 3. 

On a related note. Currently, If I queue 5 items then Paul queues one, does it play all of mine then Paul's?

**Comment by meadsteve** [comment]
@faroligo regarding the 5 of paul's then one of yours there's no special logic currently. So in your example it'd play all paul's 5 first. New issue maybe?
